[package]
name = "aoc2018"
version = "0.1.0"
authors = ["mingli <mingli@nuro.ai>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
io = "0.0.2"
regex = "1.3.1"
itertools = "0.8.2"
